[project]
name = "c-spirit-gemini-functionalities"
version = "0.1.0"
description = "C-Spirit Gemini 2.5 Flash Functionalities - Ontology development and information extraction"
authors = [
    {name = "Research Team"}
]
readme = "README.md"
requires-python = "^3.8"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
